version: '3.8'  

services:
  my-awesome-microservice:
    build:
      context: ./MyAwesomeMicroservice  
    environment:
      - DATABASE_CONNECTION_STRING=Server=db;Database=myDataBase;User=sa;Password=${SA_PASSWORD};  
    depends_on:
      - db  
    ports:
      - "8080:80"
    networks:
      testnet:
        ipv4_address: 172.10.0.12 #This is the docker network IP address of the container NOT EXTERNAL IP ADDRESS

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"  
    environment:
      ACCEPT_EULA: "Y"  
      SA_PASSWORD: "/run/secrets/sql_server_sa_password"  
      MSSQL_PID: "Developer"  
    secrets:
      - sql_server_sa_password  
    volumes:
      - db_data:/var/opt/mssql  
    ports:
      - "1901:1433"
    networks:
      testnet:
        ipv4_address: 172.10.0.11 #This is the docker network IP address of the container NOT EXTERNAL IP ADDRESS

secrets:  # Secrets help you manage sensitive information
  sql_server_sa_password:
    file: ./sql_server_sa_password.txt  # the file from which the secret will be read; should be included in your .gitignore 

volumes:
  db_data:  

networks:
  testnet:
    name: testnet-local
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/16